# Generated by Django 3.2.18 on 2023-05-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockstars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='group_path',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
