# Generated by Django 3.2.18 on 2023-05-12 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rockstars', '0002_band_group_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='bands',
            new_name='bands_id',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='contemt',
            new_name='content',
        ),
    ]
