# Generated by Django 3.2.18 on 2023-05-12 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rockstars', '0003_auto_20230512_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='bands_id',
        ),
        migrations.AddField(
            model_name='album',
            name='bands',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='band_id', to='rockstars.band'),
            preserve_default=False,
        ),
    ]
