# Generated by Django 3.2.18 on 2023-05-12 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rockstars', '0005_auto_20230512_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='band',
            new_name='bands',
        ),
    ]
